### PR TITLE
Adding `watch` option among other things

### PR DESCRIPTION
**Pull request by osartun**
* `equalHeights` is great, but it may cause problems when the browser resizes. Equalized Elements need to change their size then, but they can't because their height is set in an inline style. I added an option called `watch` that executes `equalHeights` on every `resize`.
* I documented this and the previously undocumented option `wait` and also did other changes to the Readme.
* I wrapped the auto initialization in a `$(document).ready` so that it also works when the script is executed before the DOM is ready (for example when the script is in the head). Also, I added support for specifying options with data attributes.

I didn't create the minified version yet. Please check out my changes. I'd be happy if you adopt them or at least some of them.

### CODE REVIEW

**Comment by mattbanks** [comment]
Looks great! If you want to create a minified version and add yourself to the contributors list in the readme, I can merge it in and tag a new release :)

**Comment by osartun** [comment]
Sorry, that you haven't heard back from me for over a week!
I added an `unwatch` option as I think that's necessary when there's a `watch` option.
Before I'm merging this PR I want to really test this to ensure that it works fine. I haven't gotten to that so far. I hope, it's ok with you that I keep this PR open for so long.

**Comment by osartun** [comment]
It's ready now. I made a few other significant changes:

* I moved the `equalHeightsFn` outside the `equalHeights` function and renamed it to `calcMaxHeight` (that way it's not defined every time `equalHeights` get called)
* I refactored the way `watch` works with the aim to reduce synchronous layout
* Unwatching previously watched elements also works now
* I added a section to the example page with buttons to try out the watch and unwatch options
  * In order to see the effect I made the page flexible from a window width < 960px
* The `unwatch` option is also documented now and I added myself to the contributors list
* The minified version is also created and the file is compliant to the linting rules that are in place here

Sorry, that it took so long. If you're okay with the changes I'd by happy if you merged them. :)

**Comment by mattbanks** [comment]
Looks good! I'm going to update all the version numbers and then tag a new release.

**Comment by osartun** [comment]
Awesome! :) Thanks!

**Pull request merged**
